# NB! This file was generated by LLM as I wanted to optimize time spent for reporting - the result is rough so it's to be remade

from __future__ import annotations

from html import escape
from pathlib import Path
from typing import Any

import pandas as pd

from sae_feature_atlas.config.schema import ExperimentConfig
from sae_feature_atlas.report.plots import generate_html_tables, generate_plots


# -----------------------------------------------------------------------------
# Small, dependency-free report helpers
# -----------------------------------------------------------------------------


def _shape(path: Path) -> str:
    if not path.exists():
        return "missing"
    try:
        return str(pd.read_parquet(path).shape)
    except Exception:
        return "unreadable"


def _read(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_parquet(path)
    except Exception:
        return pd.DataFrame()


def _num(value: Any, default: float = 0.0) -> float:
    try:
        if pd.isna(value):
            return default
        return float(value)
    except Exception:
        return default


def _fmt(value: Any, digits: int = 4) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass
    if isinstance(value, float):
        return f"{value:.{digits}g}"
    text = str(value)
    return text


def _pct(part: int | float, whole: int | float) -> str:
    whole = float(whole or 0)
    if whole <= 0:
        return "0.0%"
    return f"{100.0 * float(part) / whole:.1f}%"


def _safe_int(value: Any) -> int:
    try:
        if pd.isna(value):
            return 0
        return int(value)
    except Exception:
        return 0


def _count(df: pd.DataFrame, column: str, value: str) -> int:
    if df.empty or column not in df.columns:
        return 0
    return int(df[column].astype(str).eq(value).sum())


def _value_counts(df: pd.DataFrame, column: str, n: int = 12) -> pd.Series:
    if df.empty or column not in df.columns:
        return pd.Series(dtype="int64")
    return df[column].value_counts(dropna=False).head(n)


def _markdown_table(df: pd.DataFrame, columns: list[str], n: int = 10) -> str:
    """Render a small dataframe preview as markdown without optional deps.

    pandas.DataFrame.to_markdown requires the optional `tabulate` package. Reports
    should work in a minimal install, so we render compact tables ourselves.
    """
    if df is None or df.empty:
        return "_No rows available._"

    keep = [col for col in columns if col in df.columns]
    if not keep:
        return "_No requested columns available._"

    preview = df[keep].head(n).copy()

    def fmt(value: Any) -> str:
        text = _fmt(value)
        text = text.replace("\n", " ").replace("|", "\\|")
        if len(text) > 120:
            text = text[:117] + "..."
        return text

    header = "| " + " | ".join(keep) + " |"
    separator = "| " + " | ".join(["---"] * len(keep)) + " |"
    rows = ["| " + " | ".join(fmt(row[col]) for col in keep) + " |" for _, row in preview.iterrows()]
    return "\n".join([header, separator, *rows])


def _html_attrs(attrs: dict[str, str]) -> str:
    return " ".join(f'{escape(k)}="{escape(v)}"' for k, v in attrs.items() if v is not None)


def _tag(name: str, content: str, **attrs: str) -> str:
    attr = _html_attrs(attrs)
    if attr:
        return f"<{name} {attr}>{content}</{name}>"
    return f"<{name}>{content}</{name}>"


def _pill(text: str, kind: str = "neutral") -> str:
    return f'<span class="pill pill-{escape(kind)}">{escape(text)}</span>'


def _metric_card(label: str, value: Any, description: str, kind: str = "neutral") -> str:
    return f"""
    <article class="metric-card metric-{escape(kind)}">
      <div class="metric-label">{escape(label)}</div>
      <div class="metric-value">{escape(str(value))}</div>
      <p>{escape(description)}</p>
    </article>
    """


def _counts_table_html(counts: pd.Series, label_name: str = "Label", value_name: str = "Count") -> str:
    if counts.empty:
        return '<p class="muted">No values available.</p>'
    rows = []
    total = int(counts.sum())
    for label, value in counts.items():
        label_text = "missing" if pd.isna(label) else str(label)
        rows.append(
            "<tr>"
            f"<td><code>{escape(label_text)}</code></td>"
            f"<td>{int(value):,}</td>"
            f"<td>{escape(_pct(int(value), total))}</td>"
            "</tr>"
        )
    return (
        '<table class="compact-table">'
        f"<thead><tr><th>{escape(label_name)}</th><th>{escape(value_name)}</th><th>Share</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def _top_rows_html(df: pd.DataFrame, columns: list[str], n: int = 10) -> str:
    if df is None or df.empty:
        return '<p class="muted">No rows available.</p>'
    keep = [col for col in columns if col in df.columns]
    if not keep:
        return '<p class="muted">No requested columns available.</p>'

    rows = []
    for _, row in df[keep].head(n).iterrows():
        cells = []
        for col in keep:
            value = _fmt(row[col])
            if len(value) > 140:
                value = value[:137] + "..."
            if col.endswith("reason") or col.endswith("labels"):
                cells.append(f"<td class=\"wide-cell\">{escape(value)}</td>")
            elif col == "feature_id":
                cells.append(f"<td><code>{escape(value)}</code></td>")
            else:
                cells.append(f"<td>{escape(value)}</td>")
        rows.append("<tr>" + "".join(cells) + "</tr>")

    headers = "".join(f"<th>{escape(col)}</th>" for col in keep)
    return f'<div class="table-scroll"><table class="data-table"><thead><tr>{headers}</tr></thead><tbody>{"".join(rows)}</tbody></table></div>'


# -----------------------------------------------------------------------------
# Human explanations shown in reports
# -----------------------------------------------------------------------------


PLOT_CATALOG: dict[str, tuple[str, str, str]] = {
    "feature_frequency_hist": (
        "Feature frequency",
        "How often SAE features appear among the saved activations.",
        "Atlas",
    ),
    "activation_p99_hist": (
        "Activation intensity",
        "Distribution of p99 activation values. Useful for finding unusually intense features.",
        "Atlas",
    ),
    "positive_features_per_token_hist": (
        "Active features per token",
        "How many SAE features are positive for each token before optional top-k storage.",
        "Core",
    ),
    "artifact_score_hist": (
        "Artifact score",
        "Automated estimate of formatting/tokenization-artifact risk.",
        "Data quality",
    ),
    "bimodality_score_hist": (
        "Bimodality candidates",
        "BIC-improvement score for two-regime activation distributions.",
        "Atlas",
    ),
    "geometry_vs_coactivation_scatter": (
        "Decoder geometry vs coactivation",
        "Each pair compares decoder-vector cosine with empirical same-token coactivation.",
        "Research",
    ),
    "geometry_quadrants_bar": (
        "Geometry/coactivation quadrants",
        "Counts of high/low geometry and high/low coactivation pair types.",
        "Research",
    ),
    "residual_pca_variance": (
        "Residual PCA variance",
        "Large-scale anisotropy of sampled residual activations.",
        "Research",
    ),
    "decoder_pca_variance": (
        "Decoder PCA variance",
        "Large-scale anisotropy of the SAE decoder feature cloud.",
        "Research",
    ),
    "decoder_feature_pca_scatter": (
        "Decoder feature PCA",
        "Low-dimensional view of SAE decoder directions.",
        "Geometry",
    ),
    "decoder_umap_by_artifact_score": (
        "Decoder UMAP by artifact score",
        "Checks whether artifact-like features cluster spatially in decoder space.",
        "Geometry",
    ),
    "decoder_umap_by_bimodality": (
        "Decoder UMAP by bimodality",
        "Checks whether activation-regime candidates occupy structured regions.",
        "Geometry",
    ),
    "decoder_umap_by_manual_priority": (
        "Decoder UMAP by priority",
        "Heuristic triage labels projected into decoder-space UMAP.",
        "Geometry",
    ),
    "decoder_lda_by_primary_label": (
        "Decoder LDA by primary label",
        "Supervised projection using heuristic labels. Diagnostic only, not a proof.",
        "Geometry",
    ),
    "coverage_effective_pc_dim_hist": (
        "Effective residual-PC dimension",
        "How concentrated each decoder direction is across sampled residual PCA components.",
        "Coverage",
    ),
    "coverage_top20_mass_hist": (
        "Residual-PC top-mass",
        "Mass concentration in leading residual PCs. Interpret carefully if only few PCA components are available.",
        "Coverage",
    ),
    "coverage_bucket_bar": (
        "Coverage buckets",
        "Feature groups by residual-space coverage profile.",
        "Coverage",
    ),
    "gca_at_10_hist": (
        "Geometry/coactivation agreement @10",
        "Overlap between decoder-nearest neighbors and empirical coactivation neighbors.",
        "Graph alignment",
    ),
    "graph_alignment_bucket_bar": (
        "Graph alignment buckets",
        "Feature-level agreement/disagreement between decoder geometry and empirical coactivation.",
        "Graph alignment",
    ),
    "steering_candidate_score_hist": (
        "Atlas steering-candidate score",
        "Candidate score for future causal steering validation; not a steering result.",
        "Candidates",
    ),
    "steering_score_vs_risk": (
        "Candidate score vs risk",
        "Candidate usefulness compared with artifact/genericness risk.",
        "Candidates",
    ),
}


TABLE_CATALOG: dict[str, tuple[str, str, str]] = {
    "feature_cards": (
        "Feature cards",
        "Canonical merged feature-level table. This is the main artifact of the atlas.",
        "Atlas",
    ),
    "top_features": (
        "Top feature statistics",
        "Most active or intense features according to raw feature statistics.",
        "Atlas",
    ),
    "top_bimodal_features": (
        "Bimodal feature candidates",
        "Features with strongest evidence for weak/high activation regimes.",
        "Atlas",
    ),
    "geometry_quadrants": (
        "Geometry/coactivation pair quadrants",
        "Pair-level comparison of decoder cosine and empirical coactivation.",
        "Research",
    ),
    "inspection_features": (
        "Inspection feature summaries",
        "Automated artifact/inspection triage for feature-level interpretation.",
        "Data quality",
    ),
    "inspection_pairs": (
        "Inspection pair summaries",
        "Pair-level artifact and coactivation-clique triage.",
        "Data quality",
    ),
    "coverage_profiles": (
        "Residual coverage profiles",
        "How decoder directions project onto sampled residual PCA components.",
        "Coverage",
    ),
    "graph_alignment": (
        "Feature graph alignment",
        "Feature-level overlap between decoder-neighbor and coactivation-neighbor graphs.",
        "Graph alignment",
    ),
    "steering_candidates": (
        "Steering candidate hypotheses",
        "Ranked hypotheses for future causal intervention experiments.",
        "Candidates",
    ),
}


METRIC_GLOSSARY: list[tuple[str, str]] = [
    ("artifact_score", "Heuristic risk that a feature is driven by formatting, punctuation, whitespace, quote tokens, or boundary effects."),
    ("semantic_score", "Heuristic inspection score for potentially interpretable features. It is not a final explanation."),
    ("token_frequency", "How often a feature appears among saved activations. In top-k mode this is frequency among stored top-k activations."),
    ("bimodality_score", "BIC improvement of a two-component activation distribution over a one-component fit."),
    ("max_decoder_cosine", "Largest cosine similarity between this feature's decoder vector and another decoder vector."),
    ("max_coactivation_jaccard", "Largest empirical same-token coactivation Jaccard score with another feature."),
    ("effective_pc_dim", "Participation-ratio style estimate of how many residual PCA components carry the decoder direction."),
    ("pc_entropy", "Entropy of the decoder direction's mass distribution over observed residual PCA components."),
    ("pc_center_of_mass", "Average residual-PC index weighted by squared decoder projection mass."),
    ("gca_at_k", "Geometry/coactivation agreement: overlap between top-k decoder neighbors and top-k coactivation neighbors."),
    ("atlas_steering_score", "Pre-steering hypothesis score. High score means worth testing causally; it is not evidence of steering success."),
    ("steering_risk_score", "Heuristic risk score for artifact/genericness/instability in future steering tests."),
]


# -----------------------------------------------------------------------------
# Markdown report
# -----------------------------------------------------------------------------


def _artifact_warnings(cards: pd.DataFrame) -> list[str]:
    if cards.empty:
        return ["- Feature cards are missing; run the `cards` step first."]

    lines: list[str] = []
    n_cards = len(cards)

    artifacts = _count(cards, "primary_label", "likely_artifact")
    if artifacts:
        lines.append(
            f"- `{artifacts}` / `{n_cards}` features are labeled `likely_artifact` ({_pct(artifacts, n_cards)}); inspect them before semantic claims."
        )

    if "artifact_score" in cards.columns:
        artifact_score = pd.to_numeric(cards["artifact_score"], errors="coerce")
        high = int((artifact_score >= 0.35).sum())
        if high:
            lines.append(f"- `{high}` features have artifact score >= 0.35.")

    if not lines:
        lines.append("- No strong artifact warning was detected by the current heuristic triage.")

    return lines


def write_markdown_summary(cfg: ExperimentConfig) -> None:
    cfg.run_reports_dir.mkdir(parents=True, exist_ok=True)

    cards = _read(cfg.feature_cards_path)
    alignment = _read(cfg.graph_alignment_path)
    coverage = _read(cfg.feature_coverage_profiles_path)
    candidates = _read(cfg.feature_steering_scores_path)

    lines: list[str] = [
        f"# SAE Feature Atlas report: `{cfg.collection.run_name}`",
        "",
        "## 1. Executive summary",
        "",
        "This report is a layered SAE analysis artifact. It starts with core activation collection, builds a reusable feature atlas, and optionally enriches feature cards with research-grade geometry metrics.",
        "",
        f"- Feature cards: `{_shape(cfg.feature_cards_path)}`",
        f"- Coverage profiles: `{_shape(cfg.feature_coverage_profiles_path)}`",
        f"- Graph alignment: `{_shape(cfg.graph_alignment_path)}`",
        f"- Steering candidates: `{_shape(cfg.feature_steering_scores_path)}`",
        "",
        "## 2. Run overview",
        "",
        f"- Model: `{cfg.model.model_name}`",
        f"- SAE: `{cfg.model.sae_release}` / `{cfg.model.sae_id}`",
        f"- Layer/hook: `{cfg.model.layer}` / `{cfg.model.hook_name}`",
        f"- Corpus: `{cfg.collection.corpus}`",
        f"- Activation mode: `{cfg.collection.activation_mode}`",
        f"- Top-k: `{cfg.collection.top_k_features_per_token}`",
        "",
        "## 3. Architectural layers",
        "",
        "- **Core toolkit**: model/SAE resolution, residual activation collection, SAE activation encoding.",
        "- **Feature atlas**: feature statistics, top examples, feature cards, coactivation, decoder geometry, bimodality, inspection.",
        "- **Research extensions**: residual-space coverage, graph alignment, steering-candidate hypotheses.",
        "",
        "## 4. Data quality and artifact warnings",
        "",
        *_artifact_warnings(cards),
        "",
        "## 5. Feature population",
        "",
        "Primary label distribution:",
        "",
        *[f"- `{idx}`: {int(value)}" for idx, value in _value_counts(cards, "primary_label").items()],
        "",
        "Manual priority distribution:",
        "",
        *[f"- `{idx}`: {int(value)}" for idx, value in _value_counts(cards, "manual_priority").items()],
        "",
        "## 6. Residual coverage",
        "",
        "Coverage describes how SAE decoder directions project onto sampled residual-activation PCA components.",
        "",
        *[f"- `{idx}`: {int(value)}" for idx, value in _value_counts(coverage, "coverage_bucket").items()],
        "",
        "## 7. Geometry/coactivation graph alignment",
        "",
        "Graph alignment compares decoder-vector nearest neighbors with empirical coactivation neighbors.",
        "",
        *[f"- `{idx}`: {int(value)}" for idx, value in _value_counts(alignment, "graph_alignment_bucket").items()],
        "",
        "## 8. Steering-candidate hypotheses",
        "",
        "These are not steering results. They are preregistered candidates for later causal validation.",
        "",
        _markdown_table(
            candidates.sort_values("atlas_steering_score", ascending=False) if "atlas_steering_score" in candidates.columns else candidates,
            [
                "feature_id",
                "primary_label",
                "atlas_steering_score",
                "steering_risk_score",
                "artifact_score",
                "gca_at_10",
                "effective_pc_dim",
                "coverage_bucket",
                "graph_alignment_bucket",
                "steering_candidate_reason",
            ],
            n=15,
        ),
        "",
        "## 9. Interpretation caveats",
        "",
        "- Feature cards are multi-evidence profiles, not final explanations.",
        "- Automated labels are heuristic triage, not ground-truth semantics.",
        "- UMAP/LDA/PCA plots are diagnostics and visual aids, not proofs of semantic clustering.",
        "- In `topk` mode, frequency means occurrence among saved top-k features, not true positive activation frequency.",
        "- Steering-candidate scores are hypotheses for later intervention experiments, not causal evidence.",
        "- Coverage metrics depend on the sampled residual activations and the number of PCA components available.",
        "",
        "## 10. Metric glossary",
        "",
        *[f"- `{name}`: {description}" for name, description in METRIC_GLOSSARY],
        "",
    ]

    cfg.summary_md_path.write_text("\n".join(lines), encoding="utf-8")


# -----------------------------------------------------------------------------
# HTML report
# -----------------------------------------------------------------------------


def _relative_report_path(report_dir: Path, path: str | Path) -> str:
    path = Path(path)
    try:
        return str(path.relative_to(report_dir))
    except Exception:
        if path.parent.name in {"plots", "tables"}:
            return f"{path.parent.name}/{path.name}"
        return str(path)


def _plot_card(report_dir: Path, name: str, path: str) -> str:
    title, description, group = PLOT_CATALOG.get(name, (name.replace("_", " ").title(), "Generated diagnostic plot.", "Other"))
    rel = _relative_report_path(report_dir, path)
    return f"""
    <article class="plot-card" data-group="{escape(group)}">
      <a href="{escape(rel)}"><img src="{escape(rel)}" alt="{escape(title)}" loading="lazy" /></a>
      <div class="plot-body">
        <div class="plot-kicker">{escape(group)}</div>
        <h3>{escape(title)}</h3>
        <p>{escape(description)}</p>
      </div>
    </article>
    """


def _table_card(report_dir: Path, name: str, path: str) -> str:
    title, description, group = TABLE_CATALOG.get(name, (name.replace("_", " ").title(), "Generated table preview.", "Other"))
    rel = _relative_report_path(report_dir, path)
    return f"""
    <article class="artifact-card">
      <div class="artifact-kicker">{escape(group)}</div>
      <h3>{escape(title)}</h3>
      <p>{escape(description)}</p>
      <a class="button-link" href="{escape(rel)}">Open table</a>
    </article>
    """


def _artifact_card(title: str, description: str, path: Path) -> str:
    status = _shape(path)
    return f"""
    <article class="artifact-card">
      <h3>{escape(title)}</h3>
      <p>{escape(description)}</p>
      <div class="artifact-status">Shape/status: <code>{escape(status)}</code></div>
    </article>
    """


def _quick_findings(cards: pd.DataFrame, coverage: pd.DataFrame, alignment: pd.DataFrame, candidates: pd.DataFrame) -> str:
    findings: list[str] = []

    if not cards.empty:
        n = len(cards)
        artifacts = _count(cards, "primary_label", "likely_artifact")
        unlabeled = _count(cards, "primary_label", "unlabeled")
        findings.append(f"{n:,} feature cards were generated; {unlabeled:,} remain unlabeled by conservative triage.")
        if artifacts:
            findings.append(f"{artifacts:,} features are currently likely-artifact candidates and should not be used for semantic claims without inspection.")

    if not alignment.empty and "graph_alignment_bucket" in alignment.columns:
        counts = alignment["graph_alignment_bucket"].value_counts()
        disagreement = _safe_int(counts.get("geometry_coactivation_disagreement", 0))
        strong = _safe_int(counts.get("strong_geometry_coactivation_agreement", 0))
        findings.append(f"Graph alignment found {strong:,} strong geometry/coactivation agreement candidates and {disagreement:,} disagreement cases.")

    if not coverage.empty and "coverage_bucket" in coverage.columns:
        top_bucket = coverage["coverage_bucket"].value_counts().head(1)
        if not top_bucket.empty:
            findings.append(f"Most common residual-coverage bucket: {top_bucket.index[0]} ({int(top_bucket.iloc[0]):,} features).")

    if not candidates.empty:
        findings.append(f"{len(candidates):,} steering-candidate hypotheses were produced for future causal validation.")

    if not findings:
        findings.append("No feature-card artifacts were available. Run the atlas or research preset first.")

    return "<ul>" + "".join(f"<li>{escape(item)}</li>" for item in findings) + "</ul>"


def _html_document(title: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{escape(title)}</title>
  <style>
    :root {{
      --bg: #f4f7fb;
      --panel: #ffffff;
      --panel-soft: #f8fafc;
      --text: #172033;
      --muted: #64748b;
      --border: #dbe4ef;
      --brand: #2563eb;
      --brand-dark: #1e3a8a;
      --good: #047857;
      --warn: #b45309;
      --bad: #b91c1c;
      --shadow: 0 14px 40px rgba(15, 23, 42, 0.08);
      --radius: 18px;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: radial-gradient(circle at top left, #e0edff 0, transparent 34rem), var(--bg);
      color: var(--text);
      font: 15px/1.55 Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    a {{ color: var(--brand); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    main {{ max-width: 1240px; margin: 0 auto; padding: 32px 22px 72px; }}
    .hero {{
      background: linear-gradient(135deg, #111827, #172554 55%, #1e3a8a);
      color: white;
      border-radius: 26px;
      padding: 34px 38px;
      box-shadow: var(--shadow);
      margin-bottom: 24px;
    }}
    .hero h1 {{ margin: 0 0 10px; font-size: 34px; letter-spacing: -0.03em; }}
    .hero p {{ color: #dbeafe; max-width: 860px; margin: 0; }}
    .run-chip {{
      display: inline-flex;
      margin-top: 18px;
      padding: 6px 10px;
      border-radius: 999px;
      background: rgba(255,255,255,0.12);
      color: #e0f2fe;
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      font-size: 12px;
    }}
    .nav {{
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      margin: 18px 0 24px;
    }}
    .nav a {{
      display: inline-flex;
      padding: 8px 12px;
      border: 1px solid var(--border);
      border-radius: 999px;
      background: rgba(255,255,255,0.75);
      color: #334155;
      font-weight: 650;
    }}
    section {{
      background: rgba(255,255,255,0.92);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 24px;
      margin: 18px 0;
      box-shadow: 0 2px 10px rgba(15, 23, 42, 0.035);
    }}
    section h2 {{ margin: 0 0 12px; font-size: 23px; letter-spacing: -0.02em; }}
    section > p {{ color: var(--muted); max-width: 920px; }}
    .grid {{ display: grid; gap: 16px; }}
    .grid-3 {{ grid-template-columns: repeat(3, minmax(0, 1fr)); }}
    .grid-2 {{ grid-template-columns: repeat(2, minmax(0, 1fr)); }}
    .metric-grid {{ display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 14px; }}
    .metric-card, .artifact-card, .plot-card, .explain-card {{
      background: var(--panel-soft);
      border: 1px solid var(--border);
      border-radius: 16px;
      padding: 16px;
    }}
    .metric-label, .artifact-kicker, .plot-kicker {{
      color: var(--muted);
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      font-weight: 800;
    }}
    .metric-value {{ font-size: 30px; font-weight: 850; letter-spacing: -0.04em; margin: 4px 0; }}
    .metric-card p, .artifact-card p, .plot-card p, .explain-card p {{ margin: 6px 0 0; color: var(--muted); }}
    .metric-good {{ border-color: rgba(4, 120, 87, 0.25); }}
    .metric-warn {{ border-color: rgba(180, 83, 9, 0.28); }}
    .metric-bad {{ border-color: rgba(185, 28, 28, 0.28); }}
    .layer-card strong {{ display: block; font-size: 17px; margin-bottom: 6px; }}
    .plot-grid {{ display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }}
    .plot-card {{ padding: 0; overflow: hidden; background: white; }}
    .plot-card img {{ width: 100%; display: block; background: white; border-bottom: 1px solid var(--border); }}
    .plot-body {{ padding: 14px 16px 16px; }}
    .plot-body h3, .artifact-card h3, .explain-card h3 {{ margin: 4px 0 6px; font-size: 17px; }}
    .compact-table, .data-table {{ width: 100%; border-collapse: collapse; }}
    .compact-table th, .compact-table td, .data-table th, .data-table td {{
      border-bottom: 1px solid var(--border);
      padding: 8px 10px;
      text-align: left;
      vertical-align: top;
    }}
    .compact-table th, .data-table th {{ color: #334155; font-size: 12px; text-transform: uppercase; letter-spacing: 0.06em; }}
    .table-scroll {{ overflow-x: auto; border: 1px solid var(--border); border-radius: 14px; background: white; }}
    .wide-cell {{ min-width: 280px; }}
    code {{ background: #eaf1ff; color: #1e3a8a; padding: 2px 5px; border-radius: 6px; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 0.92em; }}
    .muted {{ color: var(--muted); }}
    .button-link {{
      display: inline-flex;
      margin-top: 10px;
      padding: 8px 11px;
      border-radius: 10px;
      background: #eaf1ff;
      color: #1e40af;
      font-weight: 700;
    }}
    .artifact-status {{ margin-top: 10px; color: var(--muted); }}
    .callout {{
      border-left: 4px solid var(--brand);
      background: #eff6ff;
      padding: 12px 14px;
      border-radius: 12px;
      color: #1e3a8a;
    }}
    details {{ border: 1px solid var(--border); border-radius: 14px; padding: 12px 14px; background: #fff; }}
    summary {{ cursor: pointer; font-weight: 750; }}
    pre {{ white-space: pre-wrap; background: #0f172a; color: #e5e7eb; padding: 16px; border-radius: 12px; overflow-x: auto; }}
    @media (max-width: 900px) {{
      .grid-3, .grid-2, .metric-grid, .plot-grid {{ grid-template-columns: 1fr; }}
      main {{ padding: 18px 14px 56px; }}
      .hero {{ padding: 24px; }}
    }}
  </style>
</head>
<body>
{body}
</body>
</html>
"""


def write_html_report(cfg: ExperimentConfig) -> None:
    cfg.run_reports_dir.mkdir(parents=True, exist_ok=True)

    # Generate external artifacts first. The index page will embed plots and link tables with explanations.
    plots = generate_plots(cfg.run_data_dir, cfg.run_reports_dir)
    tables = generate_html_tables(cfg.run_data_dir, cfg.run_reports_dir)

    cards = _read(cfg.feature_cards_path)
    coverage = _read(cfg.feature_coverage_profiles_path)
    alignment = _read(cfg.graph_alignment_path)
    candidates = _read(cfg.feature_steering_scores_path)

    n_cards = len(cards)
    n_artifacts = _count(cards, "primary_label", "likely_artifact")
    n_candidates = len(candidates)
    n_strong_alignment = 0
    if not alignment.empty and "graph_alignment_bucket" in alignment.columns:
        n_strong_alignment = _safe_int(alignment["graph_alignment_bucket"].value_counts().get("strong_geometry_coactivation_agreement", 0))

    top_candidates = candidates.sort_values("atlas_steering_score", ascending=False) if "atlas_steering_score" in candidates.columns else candidates

    artifacts = [
        _artifact_card("Feature cards", "Canonical merged feature-level table. This is the main output most users should inspect first.", cfg.feature_cards_path),
        _artifact_card("Feature statistics", "Frequency and activation-intensity statistics for observed SAE features.", cfg.feature_stats_path),
        _artifact_card("Top examples", "Highest-activation token contexts for each feature.", cfg.top_examples_path),
        _artifact_card("Coactivation pairs", "Empirical same-token feature coactivation pairs.", cfg.coactivation_pairs_path),
        _artifact_card("Decoder neighbors", "Nearest-neighbor graph in SAE decoder-vector space.", cfg.decoder_neighbors_path),
        _artifact_card("Bimodal candidates", "Features with candidate weak/high activation regimes.", cfg.bimodal_candidates_path),
        _artifact_card("Inspection summaries", "Automated artifact and manual-inspection triage.", cfg.inspection_feature_summaries_path),
        _artifact_card("Coverage profiles", "Residual-PCA coverage metrics for each feature.", cfg.feature_coverage_profiles_path),
        _artifact_card("Graph alignment", "Feature-level agreement between decoder geometry and empirical coactivation.", cfg.graph_alignment_path),
        _artifact_card("Steering candidates", "Pre-steering hypotheses selected from atlas metrics.", cfg.feature_steering_scores_path),
    ]

    plot_cards = "".join(_plot_card(cfg.run_reports_dir, name, path) for name, path in plots.items())
    table_cards = "".join(_table_card(cfg.run_reports_dir, name, path) for name, path in tables.items())

    summary_md = cfg.summary_md_path.read_text(encoding="utf-8") if cfg.summary_md_path.exists() else ""

    body = f"""
<main>
  <header class="hero">
    <h1>SAE Feature Atlas Report</h1>
    <p>A layered report for Gemma Scope / SAE analysis: core activation collection, reusable feature cards, and optional research-grade geometry metrics.</p>
    <span class="run-chip">{escape(cfg.collection.run_name)}</span>
  </header>

  <nav class="nav">
    <a href="#overview">Overview</a>
    <a href="#layers">Layers</a>
    <a href="#quality">Data quality</a>
    <a href="#population">Feature population</a>
    <a href="#coverage">Coverage</a>
    <a href="#alignment">Graph alignment</a>
    <a href="#candidates">Candidates</a>
    <a href="#plots">Plots</a>
    <a href="#artifacts">Artifacts</a>
    <a href="#glossary">Glossary</a>
  </nav>

  <section id="overview">
    <h2>Executive summary</h2>
    <div class="metric-grid">
      {_metric_card("Feature cards", f"{n_cards:,}", "Canonical feature-level profiles produced by the atlas.", "good")}
      {_metric_card("Likely artifacts", f"{n_artifacts:,}", "Features flagged by automated formatting/tokenization-artifact triage.", "warn" if n_artifacts else "good")}
      {_metric_card("Strong graph alignment", f"{n_strong_alignment:,}", "Features where decoder-neighbor and coactivation-neighbor graphs agree strongly.", "good")}
      {_metric_card("Steering hypotheses", f"{n_candidates:,}", "Candidates for future causal validation. These are not steering results yet.", "neutral")}
    </div>
    <div class="callout">
      <strong>Important:</strong> this report is an analysis artifact, not a proof of semantic interpretation. Use feature cards and case studies for manual validation before making mechanistic claims.
    </div>
    {_quick_findings(cards, coverage, alignment, candidates)}
  </section>

  <section id="layers">
    <h2>Project layers</h2>
    <p>The same CLI supports a lightweight toolkit mode and a deeper research mode. The feature card remains the canonical object that accumulates evidence from all enabled steps.</p>
    <div class="grid grid-3">
      <article class="explain-card layer-card"><strong>Core toolkit</strong><p>Resolve model/SAE/hook, collect residual activations, encode SAE activations, and save reusable parquet artifacts.</p></article>
      <article class="explain-card layer-card"><strong>Feature atlas</strong><p>Build feature statistics, top examples, coactivation, decoder-neighbor geometry, bimodality, inspection labels, cards, and report.</p></article>
      <article class="explain-card layer-card"><strong>Research extensions</strong><p>Add residual-space coverage, decoder/coactivation graph alignment, and steering-candidate hypotheses for later causal validation.</p></article>
    </div>
  </section>

  <section id="quality">
    <h2>Data quality and artifact triage</h2>
    <p>Artifact triage helps avoid over-interpreting features driven by punctuation, quotes, whitespace, boundary effects, or tokenization quirks.</p>
    <div class="grid grid-2">
      <div>{_counts_table_html(_value_counts(cards, "primary_label"), "Primary label", "Features")}</div>
      <div>{_counts_table_html(_value_counts(cards, "manual_priority"), "Manual priority", "Features")}</div>
    </div>
  </section>

  <section id="population">
    <h2>Feature population</h2>
    <p>These rows are a compact preview of the canonical feature-card table. Open the full generated table for broader inspection.</p>
    {_top_rows_html(cards, ["feature_id", "primary_label", "manual_priority", "token_frequency", "p99_activation", "artifact_score", "semantic_score", "bimodality_score"], n=16)}
  </section>

  <section id="coverage">
    <h2>Residual-space coverage</h2>
    <p>Coverage metrics quantify where SAE decoder directions sit relative to the sampled residual-activation PCA basis. They address whether SAE directions align with high-variance or more distributed residual components.</p>
    <div class="grid grid-2">
      <div>{_counts_table_html(_value_counts(coverage, "coverage_bucket"), "Coverage bucket", "Features")}</div>
      <div class="explain-card"><h3>How to read this</h3><p><code>effective_pc_dim</code> and <code>pc_entropy</code> describe whether a decoder direction is concentrated in a few residual PCs or spread across many. Coverage depends on the sampled residuals and the number of PCA components computed.</p></div>
    </div>
    {_top_rows_html(cards, ["feature_id", "primary_label", "pc_norm_mass_top_20", "effective_pc_dim", "pc_entropy", "pc_center_of_mass", "coverage_bucket"], n=12)}
  </section>

  <section id="alignment">
    <h2>Decoder geometry vs empirical coactivation</h2>
    <p>Graph alignment compares two notions of feature relatedness: closeness of decoder directions and empirical coactivation on tokens. Agreement suggests coherent neighborhoods; disagreement is often scientifically interesting.</p>
    <div class="grid grid-2">
      <div>{_counts_table_html(_value_counts(alignment, "graph_alignment_bucket"), "Alignment bucket", "Features")}</div>
      <div class="explain-card"><h3>Key metric</h3><p><code>GCA@k</code> is the overlap between the top-k decoder-neighbor set and top-k coactivation-neighbor set. High values mean geometry and usage agree.</p></div>
    </div>
    {_top_rows_html(cards, ["feature_id", "primary_label", "gca_at_5", "gca_at_10", "gca_at_20", "graph_alignment_bucket", "max_decoder_cosine", "max_coactivation_jaccard"], n=12)}
  </section>

  <section id="candidates">
    <h2>Steering-candidate hypotheses</h2>
    <p>These candidates are selected for future causal intervention experiments. A high score means the feature is worth testing; it does not mean steering has already succeeded.</p>
    {_top_rows_html(top_candidates, ["feature_id", "primary_label", "manual_priority", "atlas_steering_score", "steering_risk_score", "artifact_score", "semantic_score", "gca_at_10", "effective_pc_dim", "coverage_bucket", "graph_alignment_bucket", "steering_candidate_reason"], n=20)}
  </section>

  <section id="plots">
    <h2>Diagnostic plots</h2>
    <p>Plots are grouped by the layer of evidence they support. They are visual diagnostics; use the tables and feature examples for validation.</p>
    <div class="plot-grid">{plot_cards or '<p class="muted">No plots were generated.</p>'}</div>
  </section>

  <section id="tables">
    <h2>Generated table previews</h2>
    <p>These HTML tables are previews of generated parquet artifacts. The canonical data remains in <code>data/processed/&lt;run&gt;/</code>.</p>
    <div class="grid grid-3">{table_cards or '<p class="muted">No tables were generated.</p>'}</div>
  </section>

  <section id="artifacts">
    <h2>Artifact map</h2>
    <p>This section explains what each generated artifact is for.</p>
    <div class="grid grid-2">{''.join(artifacts)}</div>
  </section>

  <section id="glossary">
    <h2>Metric glossary</h2>
    <div class="grid grid-2">
      {''.join(f'<article class="explain-card"><h3><code>{escape(name)}</code></h3><p>{escape(description)}</p></article>' for name, description in METRIC_GLOSSARY)}
    </div>
  </section>

  <section>
    <h2>Raw markdown summary</h2>
    <p>The markdown summary is kept for copying into notes or pull requests.</p>
    <details>
      <summary>Show raw markdown summary</summary>
      <pre>{escape(summary_md)}</pre>
    </details>
  </section>
</main>
"""

    cfg.html_report_path.write_text(
        _html_document(f"SAE Feature Atlas Report: {cfg.collection.run_name}", body),
        encoding="utf-8",
    )


def write_report(cfg: ExperimentConfig) -> None:
    write_markdown_summary(cfg)
    write_html_report(cfg)
